import json
import os

locales_dir = "/home/faranaiki/Git/webaiki/public/locales"

translations = {
    "pt": {
        "Academic_Transcript": "Histórico Escolar",
        "Transcript_Subtitle": "Instituto de Tecnologia de Bandung • Sistemas e Tecnologia da Informação • GPA Cumulativo:",
        "Transcript_IP": "GPA:",
        "Transcript_Passed_Credits": "Créditos Aprovados:",
        "Transcript_No": "Nº",
        "Transcript_Code": "Código",
        "Transcript_Course": "Curso",
        "Transcript_Type": "Tipo",
        "Transcript_Credits": "Créditos",
        "Transcript_Grade": "Nota",
        "Transcript_Semester": "Semestre Cursado",
        "Transcript_Grade_Conversion": "Conversão de Notas",
        "Transcript_TPB": "Ano Preparatório Comum",
        "Transcript_Sarjana": "Programa de Graduação",
        "Transcript_Type_W": "Obrigatório",
        "Transcript_Type_P": "Eletiva do Curso Principal",
        "Transcript_Type_L": "Eletiva Fora do Curso",
        "Course_MA1101": "Cálculo I",
        "Course_FI1101": "Física Básica I",
        "Course_KI1101": "Química Básica I",
        "Course_WI1101": "Pancasila (Ideologia de Estado)",
        "Course_WI1102": "Pensamento Computacional",
        "Course_WI1103": "Introdução aos Princípios de Sustentabilidade",
        "Course_WI1111": "Laboratório de Física Básica",
        "Course_WI1116": "Laboratório de Interação por Computador",
        "Course_II1200": "Introdução a Sistemas e Tecnologia da Informação",
        "Course_IF1210": "Algoritmos e Programação 1",
        "Course_WI2001": "Introdução à Engenharia e Design",
        "Course_WI2005": "Língua Indonésia",
        "Course_WI2011": "Religião Islâmica",
        "Course_WI2006": "Educação Cívica",
        "Course_WI2002": "Literacia de Dados e Inteligência Artificial",
        "Course_WI2003": "Esportes"
    },
    "ru": {
        "Academic_Transcript": "Академическая Справка",
        "Transcript_Subtitle": "Бандунгский Технологический Институт • Информационные Системы и Технологии • Совокупный Средний Балл:",
        "Transcript_IP": "Средний Балл:",
        "Transcript_Passed_Credits": "Пройденные Кредиты:",
        "Transcript_No": "№",
        "Transcript_Code": "Код",
        "Transcript_Course": "Курс",
        "Transcript_Type": "Тип",
        "Transcript_Credits": "Кредиты",
        "Transcript_Grade": "Оценка",
        "Transcript_Semester": "Пройденный Семестр",
        "Transcript_Grade_Conversion": "Конверсия Оценок",
        "Transcript_TPB": "Общий Подготовительный Год",
        "Transcript_Sarjana": "Программа Бакалавриата",
        "Transcript_Type_W": "Обязательный",
        "Transcript_Type_P": "Электив По Специальности",
        "Transcript_Type_L": "Электив Вне Специальности",
        "Course_MA1101": "Математический Анализ I",
        "Course_FI1101": "Базовая Физика I",
        "Course_KI1101": "Базовая Химия I",
        "Course_WI1101": "Панчасила (Государственная Идеология)",
        "Course_WI1102": "Вычислительное Мышление",
        "Course_WI1103": "Введение В Принципы Устойчивого Развития",
        "Course_WI1111": "Лаборатория Базовой Физики",
        "Course_WI1116": "Лаборатория Компьютерного Взаимодействия",
        "Course_II1200": "Введение В Информационные Системы И Технологии",
        "Course_IF1210": "Алгоритмы И Программирование 1",
        "Course_WI2001": "Введение В Инженерию И Проектирование",
        "Course_WI2005": "Индонезийский Язык",
        "Course_WI2011": "Исламская Религия",
        "Course_WI2006": "Граждановедение",
        "Course_WI2002": "Грамотность Данных И Искусственный Интеллект",
        "Course_WI2003": "Спорт"
    },
    "vi": {
        "Academic_Transcript": "Bảng Điểm Học Tập",
        "Transcript_Subtitle": "Viện Công Nghệ Bandung • Hệ Thống Và Công Nghệ Thông Tin • Điểm Trung Bình Tích Lũy:",
        "Transcript_IP": "GPA:",
        "Transcript_Passed_Credits": "Tín Chỉ Tích Lũy:",
        "Transcript_No": "STT",
        "Transcript_Code": "Mã",
        "Transcript_Course": "Môn Học",
        "Transcript_Type": "Loại",
        "Transcript_Credits": "Tín Chỉ",
        "Transcript_Grade": "Điểm",
        "Transcript_Semester": "Học Kỳ Đã Học",
        "Transcript_Grade_Conversion": "Chuyển Đổi Điểm",
        "Transcript_TPB": "Năm Chuẩn Bị Chung",
        "Transcript_Sarjana": "Chương Trình Cử Nhân",
        "Transcript_Type_W": "Bắt Buộc",
        "Transcript_Type_P": "Tự Chọn Trong Ngành",
        "Transcript_Type_L": "Tự Chọn Ngoài Ngành",
        "Course_MA1101": "Giải Tích I",
        "Course_FI1101": "Vật Lý Cơ Bản I",
        "Course_KI1101": "Hóa Học Cơ Bản I",
        "Course_WI1101": "Pancasila (Hệ Tư Tưởng Quốc Gia)",
        "Course_WI1102": "Tư Duy Máy Tính",
        "Course_WI1103": "Nhập Môn Các Nguyên Tắc Bền Vững",
        "Course_WI1111": "Phòng Thí Nghiệm Vật Lý Cơ Bản",
        "Course_WI1116": "Phòng Thí Nghiệm Tương Tác Máy Tính",
        "Course_II1200": "Nhập Môn Hệ Thống Và Công Nghệ Thông Tin",
        "Course_IF1210": "Thuật Toán Và Lập Trình 1",
        "Course_WI2001": "Nhập Môn Kỹ Thuật Và Thiết Kế",
        "Course_WI2005": "Tiếng Indonesia",
        "Course_WI2011": "Tôn Giáo Hồi Giáo",
        "Course_WI2006": "Giáo Dục Công Dân",
        "Course_WI2002": "Hiểu Biết Dữ Liệu Và Trí Tuệ Nhân Tạo",
        "Course_WI2003": "Thể Thao"
    },
    "zh": {
        "Academic_Transcript": "成绩单",
        "Transcript_Subtitle": "万隆理工学院 • 信息系统与技术 • 累积 GPA:",
        "Transcript_IP": "GPA:",
        "Transcript_Passed_Credits": "已获学分:",
        "Transcript_No": "序号",
        "Transcript_Code": "代码",
        "Transcript_Course": "课程",
        "Transcript_Type": "类型",
        "Transcript_Credits": "学分",
        "Transcript_Grade": "成绩",
        "Transcript_Semester": "修读学期",
        "Transcript_Grade_Conversion": "成绩转换",
        "Transcript_TPB": "共同预科年",
        "Transcript_Sarjana": "本科项目",
        "Transcript_Type_W": "必修",
        "Transcript_Type_P": "专业选修",
        "Transcript_Type_L": "跨专业选修",
        "Course_MA1101": "微积分 I",
        "Course_FI1101": "基础物理 I",
        "Course_KI1101": "基础化学 I",
        "Course_WI1101": "建国五项原则 (国家意识形态)",
        "Course_WI1102": "计算思维",
        "Course_WI1103": "可持续发展原则导论",
        "Course_WI1111": "基础物理实验室",
        "Course_WI1116": "计算机交互实验室",
        "Course_II1200": "信息系统与技术导论",
        "Course_IF1210": "算法与编程 1",
        "Course_WI2001": "工程与设计导论",
        "Course_WI2005": "印尼语",
        "Course_WI2011": "伊斯兰教",
        "Course_WI2006": "公民教育",
        "Course_WI2002": "数据素养与人工智能",
        "Course_WI2003": "体育"
    }
}

for locale, trans in translations.items():
    file_path = os.path.join(locales_dir, f"{locale}.json")
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    # Add or update translations
    for k, v in trans.items():
        data[k] = v
        
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

print("Translation files updated successfully.")
