import json
import os

locales_dir = "/home/faranaiki/Git/webaiki/public/locales"

data = {
    "es": {
        "Academic_Transcript": "Expediente Académico",
        "Transcript_Subtitle": "Instituto de Tecnología de Bandung • Sistemas y Tecnologías de la Información • Promedio Acumulado:",
        "Transcript_IP": "Promedio:",
        "Transcript_Passed_Credits": "Créditos Aprobados:",
        "Transcript_No": "No",
        "Transcript_Code": "Código",
        "Transcript_Course": "Curso",
        "Transcript_Type": "Tipo",
        "Transcript_Credits": "Créditos",
        "Transcript_Grade": "Calificación",
        "Transcript_Semester": "Semestre Cursado",
        "Transcript_Grade_Conversion": "Conversión de Calificación",
        "Transcript_TPB": "Año Preparatorio Común",
        "Transcript_Sarjana": "Programa de Grado",
        "Transcript_Type_W": "Obligatorio",
        "Transcript_Type_P": "Optativa de Especialidad",
        "Transcript_Type_L": "Optativa Externa",
        "Course_MA1101": "Cálculo I",
        "Course_FI1101": "Física Básica I",
        "Course_KI1101": "Química Básica I",
        "Course_WI1101": "Pancasila (Ideología de Estado)",
        "Course_WI1102": "Pensamiento Computacional",
        "Course_WI1103": "Introducción a los Principios de Sostenibilidad",
        "Course_WI1111": "Laboratorio de Física Básica",
        "Course_WI1116": "Laboratorio de Interacción Informática",
        "Course_II1200": "Introducción a Sistemas y Tecnologías de la Información",
        "Course_IF1210": "Algoritmos y Programación 1",
        "Course_WI2001": "Introducción a la Ingeniería y el Diseño",
        "Course_WI2005": "Idioma Indonesio",
        "Course_WI2011": "Religión Islámica",
        "Course_WI2006": "Educación Cívica",
        "Course_WI2002": "Alfabetización de Datos e Inteligencia Artificial",
        "Course_WI2003": "Deportes"
    },
    "fr": {
        "Academic_Transcript": "Relevé de Notes",
        "Transcript_Subtitle": "Institut de Technologie de Bandung • Systèmes et Technologies de l'Information • Moyenne Générale :",
        "Transcript_IP": "Moyenne :",
        "Transcript_Passed_Credits": "Crédits Validés :",
        "Transcript_No": "N°",
        "Transcript_Code": "Code",
        "Transcript_Course": "Cours",
        "Transcript_Type": "Type",
        "Transcript_Credits": "Crédits",
        "Transcript_Grade": "Note",
        "Transcript_Semester": "Semestre Suivi",
        "Transcript_Grade_Conversion": "Conversion de Note",
        "Transcript_TPB": "Année Préparatoire Commune",
        "Transcript_Sarjana": "Programme de Licence",
        "Transcript_Type_W": "Obligatoire",
        "Transcript_Type_P": "Option de Spécialité",
        "Transcript_Type_L": "Option Hors Spécialité",
        "Course_MA1101": "Calculus I",
        "Course_FI1101": "Physique Fondamentale I",
        "Course_KI1101": "Chimie Fondamentale I",
        "Course_WI1101": "Pancasila (Idéologie d'État)",
        "Course_WI1102": "Pensée Informatique",
        "Course_WI1103": "Introduction aux Principes de Durabilité",
        "Course_WI1111": "Laboratoire de Physique Fondamentale",
        "Course_WI1116": "Laboratoire d'Interaction Informatique",
        "Course_II1200": "Introduction aux Systèmes et Technologies de l'Information",
        "Course_IF1210": "Algorithmique et Programmation 1",
        "Course_WI2001": "Introduction à l'Ingénierie et au Design",
        "Course_WI2005": "Langue Indonésienne",
        "Course_WI2011": "Religion Islamique",
        "Course_WI2006": "Éducation Civique",
        "Course_WI2002": "Littératie des Données et Intelligence Artificielle",
        "Course_WI2003": "Sports"
    },
    "ha": {
        "Academic_Transcript": "Takardar Shaidar Karatu",
        "Transcript_Subtitle": "Institut Teknologi Bandung • Tsari da Fasahar Bayanai • Matsakaicin Makin Sakamako:",
        "Transcript_IP": "Matsakaicin Maki:",
        "Transcript_Passed_Credits": "Kiredit da aka Ci:",
        "Transcript_No": "Lamba",
        "Transcript_Code": "Lambar Kwas",
        "Transcript_Course": "Kwas",
        "Transcript_Type": "Iri",
        "Transcript_Credits": "Kiredit",
        "Transcript_Grade": "Maki",
        "Transcript_Semester": "Zangon Karatu",
        "Transcript_Grade_Conversion": "Canza Maki",
        "Transcript_TPB": "Shekarar Shirye-shiryen Bai ɗaya",
        "Transcript_Sarjana": "Shirin Digiri na Farko",
        "Transcript_Type_W": "Wajibi",
        "Transcript_Type_P": "Zabi Cikin Kwas",
        "Transcript_Type_L": "Zabi Wajen Kwas",
        "Course_MA1101": "Kalkulus I",
        "Course_FI1101": "Fiziyya ta Farko I",
        "Course_KI1101": "Kimiya ta Farko I",
        "Course_WI1101": "Pancasila (Akidar Kasa)",
        "Course_WI1102": "Tunanin Kwamfuta",
        "Course_WI1103": "Gabatarwa ga Ka'idojin Dorewa",
        "Course_WI1111": "Dakin Gwajin Fiziyya ta Farko",
        "Course_WI1116": "Dakin Gwajin Mu'amala da Kwamfuta",
        "Course_II1200": "Gabatarwa ga Tsari da Fasahar Bayanai",
        "Course_IF1210": "Algorithm da Shirye-shirye 1",
        "Course_WI2001": "Gabatarwa ga Injiniyanci da Tsari",
        "Course_WI2005": "Harshen Indonesiya",
        "Course_WI2011": "Addinin Musulunci",
        "Course_WI2006": "Ilimin Dan Kasa",
        "Course_WI2002": "Fahimtar Bayanai da Ilimin Fasahar Zamani",
        "Course_WI2003": "Wasanni"
    },
    "he": {
        "Academic_Transcript": "גיליון ציונים אקדמי",
        "Transcript_Subtitle": "מכון הטכנולוגיה של בנדונג • מערכות וטכנולוגיות מידע • ממוצע ציונים מצטבר:",
        "Transcript_IP": "ממוצע ציונים:",
        "Transcript_Passed_Credits": "נקודות זכות שעברו:",
        "Transcript_No": "מס'",
        "Transcript_Code": "קוד",
        "Transcript_Course": "קורס",
        "Transcript_Type": "סוג",
        "Transcript_Credits": "נקודות זכות",
        "Transcript_Grade": "ציון",
        "Transcript_Semester": "סמסטר נלמד",
        "Transcript_Grade_Conversion": "המרת ציון",
        "Transcript_TPB": "שנת מכינה משותפת",
        "Transcript_Sarjana": "תואר ראשון",
        "Transcript_Type_W": "חובה",
        "Transcript_Type_P": "בחירה במסלול",
        "Transcript_Type_L": "בחירה מחוץ למסלול",
        "Course_MA1101": "חדו\"א 1",
        "Course_FI1101": "פיזיקה בסיסית 1",
        "Course_KI1101": "כימיה בסיסית 1",
        "Course_WI1101": "פנצ'סילה (אידיאולוגיית המדינה)",
        "Course_WI1102": "חשיבה חישובית",
        "Course_WI1103": "מבוא לעקרונות קיימות",
        "Course_WI1111": "מעבדה לפיזיקה בסיסית",
        "Course_WI1116": "מעבדה לאינטראקציית מחשב",
        "Course_II1200": "מבוא למערכות וטכנולוגיות מידע",
        "Course_IF1210": "אלגוריתמים ותכנות 1",
        "Course_WI2001": "מבוא להנדסה ועיצוב",
        "Course_WI2005": "השפה האינדונזית",
        "Course_WI2011": "דת האסלאם",
        "Course_WI2006": "אזרחות",
        "Course_WI2002": "אוריינות נתונים ובינה מלאכותית",
        "Course_WI2003": "ספורט"
    }
}

for lang, translations in data.items():
    file_path = os.path.join(locales_dir, f"{lang}.json")
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            content = json.load(f)
            
        for k, v in translations.items():
            content[k] = v
            
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(content, f, ensure_ascii=False, indent=2)
            f.write("\n")
